### ISSUE TITLE
problems while installing

### ISSUE THREAD

**Issue by Abdessamad139** [yakuzan/boiler#57]
this is a wonderful idea, thanks for sharing it .
i have problems while trying to install this **package locally**, could you provide the right way to install it and how to use it
thanks in advance

**Comment by yoeunes** [comment]
hmm thank's for your interest, just run the composer require command  : 
```php
composer require yakuzan/boiler
```
you can look at the code or  wait for the complete documentation ^^

**Comment by Abdessamad139** [comment]
that's solved my problem, thank you
